spring.application.name=bytewallet
server.servlet.context-path=/bytewallet

# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bytewalletdb
spring.datasource.username=postgres
spring.datasource.password=lavanere

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true